"""add_deduplication_fields

Revision ID: ff497bbd6067
Revises: 
Create Date: 2025-10-17 18:24:20.068640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff497bbd6067'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('pdf_type', sa.String(length=10), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_pdf_file_hash')
    )
    op.create_index(op.f('ix_pdfs_file_hash'), 'pdfs', ['file_hash'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pdf_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_id', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'amount', 'employee_id', 'transaction_type', name='uq_transaction_content')
    )
    op.create_index('idx_content_fingerprint', 'transactions', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_content_fingerprint'), 'transactions', ['content_fingerprint'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('car_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('date_score', sa.Float(), nullable=True),
    sa.Column('amount_score', sa.Float(), nullable=True),
    sa.Column('employee_score', sa.Float(), nullable=True),
    sa.Column('merchant_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('manually_reviewed', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('exported', sa.Boolean(), nullable=True),
    sa.Column('export_path', sa.Text(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['receipt_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_index(op.f('ix_transactions_content_fingerprint'), table_name='transactions')
    op.drop_index('idx_content_fingerprint', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_pdfs_file_hash'), table_name='pdfs')
    op.drop_table('pdfs')
    # ### end Alembic commands ###
